### ISSUE TITLE
EsCatalyst 读取ES date 类型出错

### ISSUE THREAD

**Issue by iodone** [edp963/moonbox#67]
当ES mapping 存在 
`{
 "receive_time": {
            "type": "date",
            "format": "epoch_millis || epoch_second || strict_date_optional_time || basic_date || yyyy-MM-dd HH:mm:ss"
          }
}` 类型
对于 receive_time field，ES是支持时间戳格式以Long和String两种方式写入的，例如 “receive_time”: 1536808923 和 “receive_time”: "1536808923" 。
对于上面的case 在 SparkUtil.dateTypeConvert 中：
会匹配到  `case (s: String, TimestampType) =>` 其最后的返回会调用 `java.sql.Timestamp.valueOf()`，该方法直接作用于"1536808923"，会导致无法解析

**Comment by fumiwork** [comment]
fixed in code
