### ISSUE TITLE
P1[core]Write Parquet/Kafka == hao

### ISSUE THREAD

**Issue by fumiwork** [edp963/moonbox#7]

**Comment by whtblktone** [comment]
write parquet:
 Step 1: mount table parquet_write_table options(type 'parquet', path 'hdfs://host:port:/path/to/dir')
 Step 2: insert into parquet_write_table select ...
write kafka：
 Step 1: mount table kafka_write_table options(type 'kafka', kafka.bootstrap.servers 'host:port', topic 'topicname')
 Step 2: insert into kafka_write_table select ...
 备注：
        其中port为broker工作端口（默认9092），而不是zk的端口；
        select查询出来的最终结果只能有两列，一列名为key，为String或者binary类型，一列名为value，  
        为String或者binary类型。
